/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_NativeLibrary */

#ifndef _Included_com_example_NativeLibrary
#define _Included_com_example_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_NativeLibrary
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_NativeLibrary_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
